### ISSUE TITLE
Passing context can become tiresome.

### ISSUE THREAD

**Issue by triss** [mathias/hum#12]
imo. makes library less suitable foe live-coding.

Having create-blah functions and curr-time find a default context some how would be nice.

How this would be created and managed is currently unclear.

**Comment by mathias** [comment]
The problem is that I don't want any concept of global state / default vars under the covers. Which makes having a default context a problem. Having each function that needs a context create one if one doesn't exist is possible, but I'm not sure whether that'd just produce confusing/surprising results. I'd have to dig into it more.

**Comment by triss** [comment]
Agreed I think.

Maybe a separate lib on top of hum could be created that makes assumptions about audio context being operated in.

**Comment by mathias** [comment]
There was some discussion about a year ago about where him came from and
what it was intended for:
https://github.com/mathias/hum/issues/2#issuecomment-30099975

The short answer being that I pulled it out of a HTML5 Canvas +
ClojureScript game I was building and thought the wrapper might be nice for
building software instruments in ClojureScript. So my initial thought is:
yes, I'd love for there to be a higher-level library on top of it for live
coding and providing niceties (like the linked Issue's idea of asking for
"a D in this octave" or perhaps "compute me a scale for this arpeggio."

The give-and-take would be ensuring that hum provides the correct
primitives for that abstraction to be powerful.

On Sunday, December 14, 2014, Tristan Strange notifications@github.com
wrote:

> Agreed I think.
> 
> Maybe a separate lib on top of hum could be created that makes assumptions
> about audio context being operated in.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mathias/hum/issues/12#issuecomment-66920510.

## 

Matt Gauger
http://blog.mattgauger.com

**Comment by triss** [comment]
ah great. it's nice to work on a well scoped project....

on that note perhaps my envelope creating stuff should move in to another project that uses hum?

**Comment by mathias** [comment]
I guess my continuing thoughts on the idea are:
- `hum` could state as its goal to provide a low-level, browser-independent wrapper around the Web Audio API. (That said, I haven't run into too many differences between browsers; there isn't a lot of work to standardize different browsers for Web Audio API like there are for other parts of browsers' JavaScript implementations.)
- On the other hand, Google Closure compiler and proper namespace importing means that providing higher-level functionality in `hum` will not stop anyone who only wants to use the lower-level interface.

**Comment by triss** [comment]
I think making that hum's goal would be a really good move. I'm always keener to use libraries when I find that I can fully grasp then. 

Separating all opinionated stuff like envelope's note triggering etc. from the WebAudio API stuff....

Now should we call the layer on top of it? buzz or whistle perhaps?

**Comment by triss** [comment]
closed since hum is probably  becoming a low level wrapper for webaudio.

**Comment by mathias** [comment]
If you want to start taking a stab at a library, I think you should be the one to name it. I don't know that I'll have the time right now to focus on a new library; the code I write for work is quite different and life outside of work has me pretty busy right now. I'd like to contribute if I can, though.

PS - I always thought naming a music library "keytar" might be a good level of dorkiness to start with :-)
